export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_INCREASE_ITEM = 'CART_INCREASE_ITEM';
export const CART_DECREASE_ITEM = 'CART_DECREASE_ITEM';
export const CART_TOTAL_ITEMS = 'CART_DECREASE_ITEM';
export const CART_DETAILS = 'CART_DECREASE_ITEM';
export const GET_ITEMS = 'GET_ITEMS';
